# Generated by Django 3.2.13 on 2022-07-04 21:20

from django.db import migrations
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userprofile_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userprofile',
            managers=[
                ('objects', users.models.UserProfileManager()),
            ],
        ),
    ]
