# Generated by Django 3.2.13 on 2022-09-20 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_userprofile_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='cgpa',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
