# Generated by Django 3.2.13 on 2022-09-20 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_student_cgpa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='cgpa',
            field=models.FloatField(blank=True, max_length=50, null=True),
        ),
    ]
