# Generated by Django 3.2.13 on 2022-08-20 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splManager', '0002_auto_20220726_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='spl_code',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
