# Generated by Django 3.2.13 on 2022-09-20 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_student_cgpa'),
        ('splManager', '0003_team_spl_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='spl',
            name='mentors',
            field=models.ManyToManyField(blank=True, null=True, related_name='spl_mentors', to='users.Teacher'),
        ),
        migrations.AddField(
            model_name='spl',
            name='students',
            field=models.ManyToManyField(blank=True, null=True, related_name='spl_students', to='users.Student'),
        ),
    ]
