# Generated by Django 3.2.13 on 2022-09-21 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('splManager', '0005_auto_20220921_1923'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='mentors',
            new_name='mentor',
        ),
    ]
