# Generated by Django 3.2.13 on 2022-09-21 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_student_cgpa'),
        ('splManager', '0006_rename_mentors_team_mentor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_mentor', to='users.teacher'),
        ),
    ]
