# Generated by Django 3.2.13 on 2022-09-21 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splManager', '0008_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
